# https://snapcraft.io/docs/snapcraft-yaml-reference
name: %{APPNAMELC} # you probably want to 'snapcraft register <name>'
title: %{APPNAME}
base: core18 # the base snap is the execution environment for this snap
version: 1.0.0 # just for humans, typically '1.2+git' or '1.3.2'
summary: %{Summary} # 79 char long summary
description: |
    %{DESCRIPTION}
confinement: devmode
grade: devel

apps:
    %{APPNAMELC}:
        command: python3 -m %{APPNAMELC}.__main__

parts:
    %{APPNAMELC}:
        plugin: python
        source: .
        python-version: python3