install:
	mkdir -p ~/.local/share/kservices5/ServiceMenus
	# Delete files for changed to be loaded
	rm -rf ~/.local/share/kservices5/ServiceMenus/Submenu.desktop ~/.local/share/kservices5/ServiceMenus/SimpleMenu.desktop
	cp Submenu.desktop SimpleMenu.desktop ~/.local/share/kservices5/ServiceMenus
